### ISSUE TITLE
Dev-docs using cargo doc

### ISSUE THREAD

**Issue by kaikai1024** [citahub/cita#220]
## Description

More comments.

## Additional Information

----------------Chinese----------------

补充注释，使用 `cargo doc` 可生成供开发者阅读的文档

**Comment by kaikai1024** [comment]
cargo publish the crates

**Comment by kaikai1024** [comment]
Why unpinned? @ouwenkg

**Comment by ouwenkg** [comment]
Sorry, that is my mistaken operation.

**Comment by kaikai1024** [comment]
> Sorry, that is my mistaken operation.

ok.It's an epic job.
