### ISSUE TITLE
A better way to create cita config

### ISSUE THREAD

**Issue by kaikai1024** [citahub/cita#221]
## Description

More friendly for uses.

## Additional Information

-------------Chinese-----------------

是否有更好的生成链配置的方法

**Comment by kaikai1024** [comment]
A proposal first

**Comment by ouwenkg** [comment]
That may be a tricky modification. 

Once we put configuration in  a file and change the way we config nodes. the integrate tests(CI) will hava a big impact.

My opinion: Making `--contract_arguments` more detailed.
```
optional arguments:
  -h, --help            show this help message and exit
  --authorities AUTHORITY[,AUTHORITY[,AUTHORITY[,AUTHORITY[, ...]]]]
                        Authorities (addresses) list.
  --chain_name CHAIN_NAME
                        Name of the new chain.
  --nodes IP:PORT[,IP:PORT[,IP:PORT[,IP:PORT[, ...]]]]
                        Node network addresses for new nodes.
  --super_admin SUPER_ADMIN
                        Address of super admin.
  --contract_arguments Contract.Argument=Value [Contract.Argument=Value ...]
                        Update constructor arguments for system contract. Can
                        be specify more than once.
  --timestamp TIMESTAMP
                        Specify a timestamp to use.
  --resource_dir RESOURCE_DIR
                        Chain resource directory.
  --grpc_port GRPC_PORT
                        grpc port for this chain
  --jsonrpc_port JSONRPC_PORT
                        jsonrpc port for this chain
  --ws_port WS_PORT     websocket port for this chain
  --enable_tls          The data is encrypted and transmitted on the network
```

**Comment by kaikai1024** [comment]
> That may be a tricky modification.
> 
> Once we put configuration in a file and change the way we config nodes. the integrate tests(CI) will hava a big impact.
> 
> My opinion: Making `--contract_arguments` more detailed.
> 
> ```
> optional arguments:
>   -h, --help            show this help message and exit
>   --authorities AUTHORITY[,AUTHORITY[,AUTHORITY[,AUTHORITY[, ...]]]]
>                         Authorities (addresses) list.
>   --chain_name CHAIN_NAME
>                         Name of the new chain.
>   --nodes IP:PORT[,IP:PORT[,IP:PORT[,IP:PORT[, ...]]]]
>                         Node network addresses for new nodes.
>   --super_admin SUPER_ADMIN
>                         Address of super admin.
>   --contract_arguments Contract.Argument=Value [Contract.Argument=Value ...]
>                         Update constructor arguments for system contract. Can
>                         be specify more than once.
>   --timestamp TIMESTAMP
>                         Specify a timestamp to use.
>   --resource_dir RESOURCE_DIR
>                         Chain resource directory.
>   --grpc_port GRPC_PORT
>                         grpc port for this chain
>   --jsonrpc_port JSONRPC_PORT
>                         jsonrpc port for this chain
>   --ws_port WS_PORT     websocket port for this chain
>   --enable_tls          The data is encrypted and transmitted on the network
> ```

first, not decide to use file yet.
second, the CI is a part job of this instead of the reason to deny it.
