### ISSUE TITLE
A test framework

### ISSUE THREAD

**Issue by kaikai1024** [citahub/cita#223]
## Description

The tests of CITA.

## Versions

develop

## Additional Information

---------------Chinese-----------------

梳理 CITA 的测试

[cita_tests](https://github.com/ononen/research/blob/master/tests.md)

**Comment by kaikai1024** [comment]
https://github.com/yangby-cryptape/cita-bench

**Comment by rainchen** [comment]
I also have a plan on this, and I'm going to use JMeter as the benchmark tool.

**Comment by kaikai1024** [comment]
Have no plan yet.

Will try to use Rust SDK in CI first.
