### ISSUE TITLE
Remove block data from rocksDB, find a better way to store it

### ISSUE THREAD

**Issue by kaikai1024** [citahub/cita#236]
## Description

Other way to store block data.

## Additional Information

-------------Chinese----------

先调研方案

**Comment by kaikai1024** [comment]
#206

**Comment by yangby-cryptape** [comment]
Since block data are readable, writable and immutable, I have a simple solution:
- Store all data into several **fixed-size** files, **sequentially**.
- Use a file to store the index (block height, file name, offset, size).

**Comment by keroro520** [comment]
> Since block data are readable, writable and immutable, I have a simple solution:
> 
> * Store all data into several **fixed-size** files, **sequentially**.
> * Use a file to store the index (block height, file name, offset, size).

Simplify above solution:

  * Store all block-data into one file, block by block, append only
  * Store mapping #{height => offset} into original RocksDB

When get certain one block-data, read offset from RocksDB, then seek and extract block-data.

However,  look before you leap ...

**Comment by yangby-cryptape** [comment]
> * Store all block-data into one file, block by block, append only
+ **A upper limit size for each single file is required.**

> * Store mapping #{height => offset} into original RocksDB
+ Only offset is not enough, size is required, too.

+ And the index is readable, writable and immutable, too.
  (**require an estimation**) So I think a file is enough (append sequentially).

+ The map from block hash to height should be stored in database.

**Comment by keroro520** [comment]
storing `size` within file is feasible.

block-entry in file:   

```
... |<-     block-n   ->|<-    block-n+1 ->|
... | tag | size | data | tag | size | data | ...
```

`tag` and `size` are fixed-size fields. So when we seek at the starting position, we can extract the size at fixed-position, and then extract the rest data.

**Comment by u2** [comment]
Not only block, but also: transactions, receipts, bloom etc.
And I think it's better to save block header and block body in different places.

https://github.com/cryptape/cita/blob/develop/cita-chain/types/src/db.rs#L28
https://github.com/cryptape/cita/blob/develop/cita-chain/types/src/extras.rs#L33

**Comment by yangby-cryptape** [comment]
> storing `size` within file is feasible.
> ... ...

I agree on [THIS](https://github.com/cryptape/cita/issues/236#issuecomment-464634649).

Then, each index can be stored as a **fixed-size** data. (`file id (4 bytes) + offset (4 bytes)`).
4 GiB file for indexes can store 536_870_912 heights, it is enough.

**Comment by yangby-cryptape** [comment]
> Not only block, but also: transactions, receipts, bloom etc.
> And I think it's better to save block header and block body in different places.
> ... ...

#### Classify Scenes

+ Data with incremental Ids (continuous).
  + If append-only: can write, can read, but no update (or can update but size is fixed)
    A group of append-only files is enough (Each file should have a upper limit size).
+ Store all key-value relationships (sparse) in database.

#### For example

Hash is a fixed-size data (32 bytes), so we can store all `height->hash` relationships in a group of append-only files, named as the regex `hashes-[0-9a-f]{16}`.
Each file has a upper limit size: 4 GiB. Then each file can store `134217728` height.
If we want to get block hash for height `h`, read the file which named `'hashes-{:016x}'.format(h / 134217728)`, seek with the offset `h % 134217728`.

This solution will use less disk and not far slow (even fast, I guess)  than store all `height->hash` relationships in a database.
