### ISSUE TITLE
Use fast map

### ISSUE THREAD

**Issue by u2** [citahub/cita#245]
It's better to use some customer fast map instead of default hasher, the rust default hasher is a bit slower.

https://github.com/paritytech/parity-ethereum/blob/master/util/fastmap/src/lib.rs#L28

When we use `H256` and other fixed-hash, we can implement a specialized version hashmap.

**Comment by yangby-cryptape** [comment]
I remember that there was a discussion about this feature already (in telegram, @quake initiated the discussion).
[CKB] probably have already finished this feature.
Maybe we can just reuse (or copy from) their crate?

[CKB]: https://github.com/nervosnetwork/ckb

**Comment by u2** [comment]
They just use FnvHashMap at the most time.

**Comment by quake** [comment]
Yes, we are considering using `PlainHasher` for H256 in CKB
