### ISSUE TITLE
[feature] Auto adjust consensus time

### ISSUE THREAD

**Issue by timmyz** [citahub/cita#275]
# Auto adjust consensus time

## Description
The default value of ```SysConfig.blockInterval``` is 3000, which means 3 seconds. The whole network will keeps this fixed interval to generate empty blocks even there is no transactions at all.
If one empty block occupied 12K, it will cost at least ```12K*3600*24*365/3/1024/1024 = 120.3G``` storage for each single node running for 1 year. 
That's quite diseconomy. So I propose to make the consensus time adjustable dynamically. E.g. we can turn down the interval to 3 secs or even 1 sec to speed up the block generation at work time / peak time, and turn up the interval to 1 hour or higher to reduce the useless storage occupation.

CITAHub Topic Reference: https://talk.citahub.com/t/topic/138, ```Eason``` replied you are working on it.

**Comment by kaikai1024** [comment]
@KaoImin

**Comment by KaoImin** [comment]
This function has already developed, however, the tests process has not finished yet.

**Comment by kaikai1024** [comment]
@timmyz 
> If one empty block occupied 12K

May i ask that where did you get the number?

I checked on my own computer, only about 1k.

**Comment by timmyz** [comment]
> @timmyz
> 
> > If one empty block occupied 12K
> 
> May i ask that where did you get the number?
> 
> I checked on my own computer, only about 1k.

@kaikai1024 
told by one of your ops named 蒋贤亮, who was introduced by 孔庆阳

**Comment by kaikai1024** [comment]
@jiangxianliang007 Please check the latest number.

**Comment by KaoImin** [comment]
The feature is testing, however, it needs the support of system contract.
If you want to read the codes, go to [https://github.com/cryptape/bft-rs/tree/develop](url) and [https://github.com/cryptape/cita-bft/tree/bft_rs_refactor](url).

**Comment by timmyz** [comment]
> The feature is testing, however, it needs the support of system contract.
> @timmyz If you want to read the codes, go to [https://github.com/cryptape/bft-rs/tree/develop](url) and [https://github.com/cryptape/cita-bft/tree/bft_rs_refactor](url).

well, i don't understand the grammar of Rust. just wait for your release and i'll try. @KaoImin

**Comment by kaikai1024** [comment]
@all-contributors please add @timmyz  for idea

**Comment by timmyz** [comment]
@kaikai1024 hi, i noticed that you had removed this from the milestone of v0.23.
may i know which version will this be implemented? i think won't be long since @KaoImin said [bft was working on it](https://talk.citahub.com/t/topic/138/5), right?

**Comment by kaikai1024** [comment]
@KaoImin until `cita-bft` is ready

**Comment by kaikai1024** [comment]
> i noticed that you had removed this from the milestone of v0.23.

yeah, 0.23.0 is coming and cita-bft still needs a little time.

**Comment by KaoImin** [comment]
> @kaikai1024 hi, i noticed that you had removed this from the milestone of v0.23.
> may i know which version will this be implemented? i think won't be long since @KaoImin said [bft was working on it](https://talk.citahub.com/t/topic/138/5), right?

The new BFT is testing, and it will come soon.
