### ISSUE TITLE
The way to reduce the disk footprint

### ISSUE THREAD

**Issue by kaikai1024** [citahub/cita#284]
## Description

How to educe the disk footprint?

* Remove the block data form rocksdb #236  It seems that it's better to write file instead of using rocksdb. @yangby-cryptape 
* Auto adjust consensus time #275 Can increase consensus time when there are less transactions.
* No empty block.
* Clear empty blocks.
* Use snapshot

Need to discuss. 

## Versions

develop

## Additional Information

-----------Chinese---------
如何减少磁盘占用空间?

* 不使用 rocksdb 存储 block data，使用文件存储好像效果更好
* 动态调整出块时间，在交易量少的时候可以增加出块时间
* 不出空块
* 清理旧的空快
* 快照

**Comment by yangby-cryptape** [comment]
> * 不使用 rocksdb 存储 block data，使用文件存储好像效果更好

I don't mean this.

Almost all sst files are used to store `CurrentHeight` and `CurrentProof`, not block data.
Remove all current statuses is enough.

**Comment by kaikai1024** [comment]
> Almost all sst files are used to store CurrentHeight and CurrentProof, not block data.
Remove all current statuses is enough.

Got it.

**Comment by kaikai1024** [comment]
But, Remove all current statuses can decrease the file number, To reduce the disk footprint still needs to remove block data from RocksDB, right? @yangby-cryptape

**Comment by kaikai1024** [comment]
#206

**Comment by yejiayu** [comment]
> No empty block.

Empty blocks don't make any sense. We can make the proposal empty block as an optional configuration item.

**Comment by kaikai1024** [comment]
> We can make the proposal empty block as an optional configuration item.

The new cita-bft will alway keep round if there are no transactions, so it will be an optional configuration of auth module if we want to do it.
