### ISSUE TITLE
CI cache mechanism optimaize

### ISSUE THREAD

**Issue by u2** [citahub/cita#286]
We can use https://github.com/holmgr/cargo-sweep to avoid the cache explosion problem in the CircleCi.

https://github.com/cryptape/cita/blob/develop/.circleci/config.yml#L75

And how about to remove the Travis ci? We have not used it anymore.

**Comment by kaikai1024** [comment]
Cool with the `cargo sweep`.

The Travis CI is now only running the test of  system contracts. and it's not required. So we'll keep it as an optional test. I will check that why it failed later.

**Comment by kaikai1024** [comment]
@u2 Please fix the muta link, that's a private project.

**Comment by yangby-cryptape** [comment]
Install `cargo-sweep` into `cita-build` or install `cargo-sweep` when running `CI`, like `cargo-audit` (has cache)?
