### ISSUE TITLE
WARNING: Published ports are discarded when using host network mode

### ISSUE THREAD

**Issue by yangby-cryptape** [citahub/cita#400]
+ In linux, run `bin/cita start`:

  https://github.com/cryptape/cita/blob/5df437406fe4c885cbc3554004b254570b12b8c1/env.sh#L52-L62

  `--net=host` and `-p` are conflicted.

+ IMHO, use `host networking` as default present a potential security risk. 

Ref: [Docker Docs: Use host networking](https://docs.docker.com/network/host/)

**Comment by kaikai1024** [comment]
> use host networking as default

That's a long history

**Comment by kaikai1024** [comment]
> If you use the host network driver for a container, that container’s network stack is not isolated from the Docker host. 

> The host networking driver only works on Linux hosts, and is not supported on Docker Desktop for Mac, Docker Desktop for Windows, or Docker EE for Windows Server.


We should use defalue network mode: bridge
