### ISSUE TITLE
The last 100 pieces of historical data from the snapshot were not saved

### ISSUE THREAD

**Issue by QingYanL** [citahub/cita#605]
## Description

[快照时最近100块的历史数据未保存，仅保存了状态]

## Steps to Reproduce

1. [创建三个共识节点： 
mac需先端口映射
 `bin/cita create --super_admin "0x4b5ae4567ad5d9fb92bc9afd6a657e6fa13a2523" --nodes "127.0.0.1:4000,127.0.0.1:4001,127.0.0.1:4002"  --enable_version --contract_arguments SysConfig.economicalModel=1`
setup并start
bin/cita setup test-chain/0到2
bin/cita start test-chain/0到2
]

2. [在块高为5(快照100块范围外), 块高为30(快照100块范围内),块高为150(快照后)的时候对不同的账户进行交易转账不同的金额(便于区分) ` transfer --address 0x0d5c23dc41956c8aca3b6f3fa581a4fd640f7997 --private-key 0x5f0258a4778057a8a7d97809bd209055b2fbafa654ce7d31ec7191066b9225e6 --value 100`]  

3. [进入docker内节点0，进行快照`../../bin/snapshot_tool -m snapshot -e 120`]
4. [新增节点3，
`./scripts/create_cita_config.py append --chain_name test-chain --node "127.0.0.1:4003" `  

使其成为共识节点： `scm NodeManager approveNode --address 0x4bf0e52ed703c9a46efaac0761a17365dc09dace --admin-private 0x5f0258a4778057a8a7d97809bd209055b2fbafa654ce7d31ec7191066b9225e6` 
查看添加共识成功：`rpc getMetaData` ]

5.[进入docker ,进入节点3对其，进行快照恢复。`cp ../0/snapshot_* ./ `
`../../bin/snapshot_tool -m restore`]

6.[快照恢复后，分别根据步骤2中交易hash，向节点3 http://127.0.0.1:1340发送 rpc getTransaction，查看交易数据是否保存 ]
  
**Expected behavior**: [快照时最近100块的历史数据保存]

**Actual behavior**: [步骤6中，仅可以查询到块高为5(快照100块范围外), 块高为30(快照100块范围内)的交易状态，查询不到数据]
![image](https://user-images.githubusercontent.com/48231505/58301218-26655200-7e18-11e9-8405-569f319bba10.png)

**Reproduce how often**: [every]

## Versions

[v0.24]

**Comment by leeyr338** [comment]
@rink1969 , 快照在设计的时候，就是仅保存最新状态，而不是所有历史数据，对吧？
我理解快照的特性设计就是这样。

**Comment by kaikai1024** [comment]
> 块高为30(快照100块范围内)的交易状态，查询不到数据]

交易状态是什么意思？  后面截图是 getTransaction 的结果吗？

**Comment by leeyr338** [comment]
块高为 5 的交易能查到应该是在你操作过程中同步过来的。

**Comment by ouwenkg** [comment]
> > 块高为30(快照100块范围内)的交易状态，查询不到数据]
> 
> 交易状态是什么意思？ 后面截图是 getTransaction 的结果吗？

就是说, 能查到变化后的余额, 但是想通过 hash 来取交易, 失败了

**Comment by janx** [comment]
现在的快照实现只是第一个版本，快照具体保存什么是可以根据需求来的。

**Comment by QingYanL** [comment]
> > 块高为30(快照100块范围内)的交易状态，查询不到数据]
> 
> 交易状态是什么意思？ 后面截图是 getTransaction 的结果吗？

仅能查询到转账账户的余额，查询不到交易详情信息，后面截图是 getTransaction 的结果

**Comment by QingYanL** [comment]
> 块高为 5 的交易能查到应该是在你操作过程中同步过来的。
> 
> 理论上讲，如果你操作时间足够快，或者你从块高为 200 之后再发交易；新增节点应该是查询不到任何历史数据的。

经测: 快照恢复是从块1到指定的块之间的数据进行了快照恢复，所以确实块高为5，能查询到交易状态；
根据CITA 文档描述，支持指定快照的前100块可保存历史数据，经测这100块内的交易是未保存数据的，仅能查询到交易结果；

**Comment by kaikai1024** [comment]
应该是有问题的，辛苦，我们会看一下的

**Comment by kaikai1024** [comment]
https://docs.citahub.com/zh-CN/next/cita/data/snapshot

**Comment by kaikai1024** [comment]
I can get the transaction...
I will check it again.

**Comment by kaikai1024** [comment]
I can get the transaction...
I will check it again.

**Comment by kaikai1024** [comment]
I check the version from `0.20` to `0.24.0`:

* 0.20, 0.23.1, 0.24.0 can use the feature, can't get the tx data.
* 0.21 and 0.22.0 can't use the feature

What version did you use the feature and get the tx data? @QingYanL

**Comment by kaikai1024** [comment]
#536
