### ISSUE TITLE
cita_cli 运行报错 源码编译报错  xxxx:permission denied

### ISSUE THREAD

**Issue by aseing-0** [citahub/cita#896]
## Description
按照文档中的“快速部署”部分，下载了相关文件并执行，
报错如下：
root@instance-1 cita_secp256k1_sha3]# bin/cita create --super_admin "0x37d1c7449bfe76fe9c445e626da06265e9377601" --nodes "127.0.0.1:4000,127.0.0.1:4001,127.0.0.1:4002,127.0.0.1:4003"
\Start docker container cita_run_container ...
5567394a8e047410fad6c6474f21a64d3229ab96a26687131c6d4c9de0cfdc74
\error: exec: "bin/cita": stat bin/cita: permission denied

## Versions
Docker version 1.13.1, build 7f2769b/1.13.1
cita-cli-x86_64-musl-tls-0.19.6.tar.gz
cita_secp256k1_sha3.tar.gz

## Additional Information
事实上我用源码也试过,而且在ubuntu18.04和centos7上都试过，在执行 sudo ./env.sh make debug 时候，报错 Makefile:permission denied。 即使用root权限也不行。 而此时直接执行make debug是能编译通过的。

**Comment by aseing-0** [comment]
[root@instance-1 cita_secp256k1_sha3]# docker ps
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS              PORTS               NAMES
5567394a8e04        cita/cita-run:ubuntu-18.04-20190829   "/usr/bin/entrypoi..."   About an hour ago   Up About an hour                        cita_run_container

**Comment by aseing-0** [comment]
HI，能否支持一下，十分感谢！

**Comment by rink1969** [comment]
这里的`permission denied`应该不是指root这种用户权限不够，而是文件没有可执行权限。
可以 `chmod +x ./bin/*` 处理一下。
这个可能跟解压缩工具，或者文件系统的设置有关。

**Comment by aseing-0** [comment]
我将所有文件都加入了可执行权限，结果没有变化  ):

[root@centos-7-1 cita_sm2_sm3]# ls -l bin
total 132456
-rwxrwxrwx. 1 root root  9119408 Oct 24 13:36 box-executor
-rwxrwxrwx. 1 root root  9075992 Oct 24 13:36 chain-executor-mock
-rwxrwxrwx. 1 root root    14278 Oct 24 13:36 cita
-rwxrwxrwx. 1 root root 13645744 Oct 24 13:36 cita-auth
-rwxrwxrwx. 1 root root  9474656 Oct 24 13:36 cita-bft
-rwxrwxrwx. 1 root root 13994240 Oct 24 13:36 cita-chain
-rwxrwxrwx. 1 root root      312 Oct 24 13:36 cita-config
-rwxrwxrwx. 1 root root     3220 Oct 24 13:36 cita-env
-rwxrwxrwx. 1 root root 16710696 Oct 24 13:36 cita-executor
-rwxrwxrwx. 1 root root  3361232 Oct 24 13:36 cita-forever
-rwxrwxrwx. 1 root root 13136904 Oct 24 13:36 cita-jsonrpc
-rwxrwxrwx. 1 root root 14489312 Oct 24 13:36 cita-network
-rwxrwxrwx. 1 root root  8362464 Oct 24 13:36 cita-relayer-parser
-rwxrwxrwx. 1 root root  8804136 Oct 24 13:36 consensus-mock
-rwxrwxrwx. 1 root root  5002608 Oct 24 13:36 create-genesis
-rwxrwxrwx. 1 root root  1809984 Oct 24 13:36 create-key-addr
-rwxrwxrwx. 1 root root  8595272 Oct 24 13:36 snapshot-tool
[root@centos-7-1 cita_sm2_sm3]# ls -l scripts/
total 32
-rwxrwxrwx. 1 root root  4276 Oct 24 13:36 amend_system_contracts.py
-rwxrwxrwx. 1 root root  1157 Oct 24 13:36 amend_system_contracts.sh
drwxrwxrwx. 4 root root    70 Oct 24 13:36 config_tool
drwxrwxrwx. 5 root root   113 Oct 24 13:36 contracts
-rwxrwxrwx. 1 root root 19743 Oct 24 13:36 create_cita_config.py
drwxrwxrwx. 3 root root    72 Oct 24 13:36 txtool
[root@centos-7-1 cita_sm2_sm3]# **bin/cita create --super_admin "0x37d1c7449bfe76fe9c445e626da06265e9377601" --nodes "127.0.0.1:4000,127.0.0.1:4001,127.0.0.1:4002,127.0.0.1:4003"
error: exec: "bin/cita": stat bin/cita: permission denied**
[root@centos-7-1 cita_sm2_sm3]# docker --version
Docker version 1.13.1, build 7f2769b/1.13.1
[root@centos-7-1 cita_sm2_sm3]# docker images
REPOSITORY                TAG                     IMAGE ID            CREATED             SIZE
docker.io/cita/cita-run   ubuntu-18.04-20190829   6161f4672676        3 months ago        589 MB

**Comment by aseing-0** [comment]
各位大佬，能帮忙看下么？ 按照cita的文档，一直没有搭出来，也还没找到问题所在。 我们打算基于cita做一些应用，可是我一直搭不出节点啊。。。

**Comment by rink1969** [comment]
把已经在跑的docker容器删掉试试。

**Comment by rink1969** [comment]
https://talk.citahub.com/t/topic/1041  这个帖子是描述的同一个问题吧。
运行环境相关的问题，在论坛里讨论吧。
跟cita本身没关系。
