### ISSUE TITLE
交易异步处理 时候，无效交易产生

### ISSUE THREAD

**Issue by lyh168** [citahub/cita#938]
交易异步处理 时候，无效交易产生，那这种无效交易什么时候进行剔除呢？如果不剔除是一直占用空间吗？

**Comment by rink1969** [comment]
CITA是先共识再执行，因此共识过的区块里可能包含有无效的交易。
无效交易不会被剔除，因为已经计算入区块hash。
但是从receipt可以看出来哪些是无效交易，无效交易的receipt为空。

如果担心恶意用户发送大量无效交易，CITA有两项措施来避免这种情况：
1. 无效交易也会扣除quota，每个块的quota是有上限的。
2. 如果开启charge模式，无效交易也是要收费的，且一旦发现用户在费用不足的情况下还多次发送无效交易，会将其列入黑名单。
